# grey: #595959
# tan: #A57F60
# green: #45462A

format = """
$username$hostname[ in](#A57F60)$directory
[ $git_branch$git_commit$git_state$git_status\
$aws\
$azure\
$c\
$container\
$golang\
$kubernetes\
$nodejs\
$package\
$perl\
$python\
$rust\
$vagrant](#595959 bold)
$time
$character"""

# Swap the prompt character
[character]
success_symbol = "[ âœ” ~â®](green bold)"
error_symbol = "[ âœ— ~â®](red bold)"

# User
[username]
style_root = "red bold"
style_user = "green"
format = "[ î¯† $user ]($style bold)"
disabled = false
show_always = true

# Directory
[directory]
truncation_length = 3
style = "#A57F60"
read_only = "ğŸ”’"
read_only_style = "bold red"
format = "[ ï¼ $path ]($style bold)[$read_only]($read_only_style)"

# Git
[git_branch]
style = "bold #A57F60"
symbol = "[ ï˜ ]($style)"
truncation_length = 10
truncation_symbol = ""

[git_commit]
style = "#A57F60"
commit_hash_length = 4
tag_symbol = "[ğŸ”– ]($style)"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold green)"

[git_status]
conflicted = "ğŸ´â€â˜ "
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](bold #A57F60)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"

# Host OS
[hostname]
ssh_only = false
style = "#A57F60"
format =  "[ïŒ’ $hostname]($style bold)"
trim_at = ".companyname.com"
disabled = false

# Time
[time]
style = "#A57F60"
disabled = false
use_12hr = true
format = '[ $time ]($style bold)'
time_format = "%a %D %I:%M %P"
utc_time_offset = "local"

# aws
[aws]
style = "#A57F60 bold"
symbol = " î­ "
format = "on [$symbol$profile]($style) "

# azure
[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ï´ƒ "
style = "#A57F60 bold"

# c
[c]
style="bold #A57F60"
format = "via [$name $version]($style)"

# container
[container]
style="bold #A57F60"
format = '[$symbol \[$name\]]($style) '

# go
[golang]
format = "via [î˜§ $version](bold #A57F60) "

# k8s
[kubernetes]
style="bold #A57F60"
format = 'on [âˆ ($user on )($cluster in )$context \($namespace\)]($style) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"root/.*" = "root"

# node
[nodejs]
style="bold #A57F60"
format = "via [îœ˜ $version]($style) "

# package
[package]
format = "via [î¬© $version](bold #A57F60) "

# perl
[perl]
format = "via [î© $version](bold #A57F60) "

# Python
[python]
symbol = "îˆµ "
style="bold #A57F60"
pyenv_version_name = true

#rust
[rust]
format = "via [î¨ $version](bold #A57F60)"

# vagrant
[vagrant]
format = "via [â± $version](bold #A57F60) "

# âˆ â² ï¼ ï˜ î‚° î­¯ â˜‘ â˜’ â˜  âœ” âœ— â–¤ â–“ â–‘ ğŸ™½ ğŸ™¼ â—¢ â—£ 
